### ISSUE TITLE
Building with latest SM

### ISSUE THREAD

**Issue by StarterX4** [thraaawn/SMJansson#8]
Tried to build Linux version, but doesn't builds with the latest SM versions (1.10, 1.11) and ends up with error
 `IShareSys.h:40:10: fatal error: sp_vm_types.h: No such file or directory`
